[package]
name = "putio"
version = "0.2.0"
authors = ["Ukang'a Dickson <ukanga@users.noreply.github.com>"]
edition = "2021"

[dependencies]
reqwest = { version = "0.11.11", features = ["blocking", "json"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
